import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

const robotoSans = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"], // Define weights explicitly
  subsets: ["latin"],
  variable: "--font-roboto-sans",
  display: "swap", // Improves loading performance
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoSans.className}>
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <SessionWrapper>
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
